import React from "react";
import Footer from "../../components/Footer";
import { FaLink, FaBullseye, FaShareAlt, FaChartLine, FaMoneyBillWave, FaRocket } from "react-icons/fa";

const Affiliate = () => {
  const steps = [
    {
      icon: <FaLink size={28} className="text-red-600" />,
      title: "Join Affiliate Programme",
      description:
        "Sign up to affiliate programmes that align with your interests and target audience.",
    },
    {
      icon: <FaBullseye size={28} className="text-blue-600" />,
      title: "Receive Unique Link",
      description:
        "After signing up, receive a unique affiliate link that tracks your sales and leads.",
    },
    {
      icon: <FaShareAlt size={28} className="text-green-600" />,
      title: "Promote Products & Services",
      description:
        "Promote products via website blogs, social media, ads, and other channels.",
    },
    {
      icon: <FaChartLine size={28} className="text-yellow-600" />,
      title: "Track Leads or Sales",
      description:
        "Monitor clicks, conversions, and actions performed through your affiliate link.",
    },
    {
      icon: <FaMoneyBillWave size={28} className="text-purple-600" />,
      title: "Commission Received",
      description:
        "Earn a percentage or fixed amount for every successful conversion you generate.",
    },
    {
      icon: <FaRocket size={28} className="text-pink-600" />,
      title: "Continuous Optimization",
      description:
        "We constantly analyze and optimize strategies to ensure higher conversions and better revenue for both affiliates and companies.",
    },
  ];

  return (
    <div className="bg-white text-gray-900 font-sans min-h-screen">
      {/* ================= HERO ================= */}
      <section className="py-20 px-6 md:px-20 text-center">
        <h1 className="text-4xl md:text-5xl font-bold mb-4">Affiliate Marketing</h1>
        <p className="text-lg md:text-xl text-gray-600 max-w-3xl mx-auto">
          Transform your website traffic into a steady stream of income with smart affiliate strategies. Performance-based marketing lets companies pay commissions for sales or leads generated by affiliates, making it a win-win scenario.
        </p>
        <img
          src="/afff.png"
          alt="Affiliate Marketing"
          className="w-full max-w-2xl mx-auto mt-10 rounded-xl "
        />
      </section>

      {/* ================= HOW AFFILIATES WORK ================= */}
      <section className="py-20 px-6 md:px-20 bg-gray-50">
        <div className="max-w-6xl mx-auto text-center mb-12">
          <h2 className="text-3xl md:text-4xl font-bold mb-4">How Affiliates Work</h2>
          <p className="text-gray-600 text-lg md:text-xl max-w-3xl mx-auto">
            Follow these steps to start earning through affiliate marketing:
          </p>
        </div>

        <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 gap-10 max-w-6xl mx-auto">
          {steps.map((step, index) => (
            <div
              key={index}
              className="bg-white rounded-xl shadow-lg p-6 flex flex-col items-center text-center hover:shadow-xl transition-shadow"
            >
              <div className="mb-4">{step.icon}</div>
              <h3 className="text-xl font-semibold mb-2">{step.title}</h3>
              <p className="text-gray-600 text-sm">{step.description}</p>
            </div>
          ))}
        </div>
      </section>

      {/* ================= FOOTER ================= */}
      <Footer />
    </div>
  );
};

export default Affiliate;
